# Generated by Django 5.2.5 on 2025-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_body',
            field=models.TextField(default=''),
        ),
    ]
